mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_1_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_1_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_50_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_50_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_100_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_100_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_300_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_300_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_500_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_500_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_1000_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_1000_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_3000_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_3000_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_5000_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_5000_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_10000_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_10000_quads.txt
mitsuba ./scenes/basic/time_complexity_increasing_quads/scene_100000_quads.xml > ./scenes/basic/time_complexity_increasing_quads/scene_100000_quads.txt