#!/usr/bin/env python3

"""
Instancias:
python scenes/scene_geometries/create_geometry.py -n=30000 -f=scenes/scene_geometries/quad_2tri.obj -d -1 0 0 -k 40 -a 0 -10 1 -b 10 10 3 -o scenes/scene_geometries/quads-k40-instances.xml -i 

No instancias:
python scenes/scene_geometries/create_geometry.py -n=30000 -f=scenes/scene_geometries/quad_2tri.obj -d -1 0 0 -k 40 -a 0 -10 1 -b 10 10 3 -o scenes/scene_geometries/quads-k40-instances.xml

"""


import argparse
import math
import random
import shlex
import sys
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple


Vec3 = Tuple[float, float, float]


SHORT_FLAG_MAP = {
	"--n-objects": "-n",
	"--obj-filename": "-f",
	"--mean-dir": "-d",
	"--kappa": "-k",
	"--min-pos": "-a",
	"--max-pos": "-b",
	"--output": "-o",
	"--seed": "-s",
	"--name-prefix": "-p",
	"--scale": "-c",
	"--up": "-u",
	"--reflectance": "-r",
	"--instances": "-i",
}


def normalize(v: Vec3) -> Vec3:
	norm = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
	if norm == 0.0:
		raise ValueError("Zero-length vector cannot be normalized.")
	return (v[0] / norm, v[1] / norm, v[2] / norm)


def cross(a: Vec3, b: Vec3) -> Vec3:
	return (
		a[1] * b[2] - a[2] * b[1],
		a[2] * b[0] - a[0] * b[2],
		a[0] * b[1] - a[1] * b[0],
	)


def orthonormal_basis(axis: Vec3) -> Tuple[Vec3, Vec3]:
	helper = (0.0, 0.0, 1.0) if abs(axis[2]) < 0.999 else (1.0, 0.0, 0.0)
	tangent = normalize(cross(helper, axis))
	bitangent = cross(axis, tangent)
	return tangent, bitangent


def sample_uniform_sphere(rng: random.Random) -> Vec3:
	z = 2.0 * rng.random() - 1.0
	phi = 2.0 * math.pi * rng.random()
	r = math.sqrt(max(0.0, 1.0 - z * z))
	return (r * math.cos(phi), r * math.sin(phi), z)


def sample_vmf(mean_dir: Vec3, kappa: float, rng: random.Random) -> Vec3:
	if kappa <= 1e-6:
		return sample_uniform_sphere(rng)

	u = rng.random()
	exp_term = math.exp(-2.0 * kappa)
	w = 1.0 + math.log(u + (1.0 - u) * exp_term) / kappa
	w = max(-1.0, min(1.0, w))

	phi = 2.0 * math.pi * rng.random()
	sin_theta = math.sqrt(max(0.0, 1.0 - w * w))
	tangent, bitangent = orthonormal_basis(mean_dir)

	x = sin_theta * math.cos(phi)
	y = sin_theta * math.sin(phi)

	direction = (
		x * tangent[0] + y * bitangent[0] + w * mean_dir[0],
		x * tangent[1] + y * bitangent[1] + w * mean_dir[1],
		x * tangent[2] + y * bitangent[2] + w * mean_dir[2],
	)
	return normalize(direction)


def format_float(value: float) -> str:
	return f"{value:.16g}"


def format_vec3(value: Vec3) -> str:
	return ", ".join(format_float(component) for component in value)


def sample_position(min_pos: Vec3, max_pos: Vec3, rng: random.Random) -> Vec3:
	return (
		rng.uniform(min_pos[0], max_pos[0]),
		rng.uniform(min_pos[1], max_pos[1]),
		rng.uniform(min_pos[2], max_pos[2]),
	)


def validate_bounds(min_pos: Vec3, max_pos: Vec3) -> None:
	if min_pos[0] > max_pos[0] or min_pos[1] > max_pos[1] or min_pos[2] > max_pos[2]:
		raise ValueError("Each component of min_pos must be <= max_pos.")


def get_short_invocation_command() -> str:
	converted_args: List[str] = []
	for token in sys.argv[1:]:
		if token in SHORT_FLAG_MAP:
			converted_args.append(SHORT_FLAG_MAP[token])
			continue

		rewritten = False
		for long_flag, short_flag in SHORT_FLAG_MAP.items():
			prefix = long_flag + "="
			if token.startswith(prefix):
				converted_args.append(short_flag + token[len(long_flag):])
				rewritten = True
				break

		if not rewritten:
			converted_args.append(token)

	return "python " + " ".join(shlex.quote(arg) for arg in [sys.argv[0], *converted_args])


def build_generation_comment(command: str) -> str:
	escaped_command = command.replace("--", "- -")
	return (
		"<!-- This file was generated by the create_geometry script, using command: -->\n"
		f"<!-- \t{escaped_command} -->"
	)


def build_xml(
	n_objects: int,
	obj_filename: str,
	mean_dir: Vec3,
	kappa: float,
	min_pos: Vec3,
	max_pos: Vec3,
	name_prefix: str,
	scale: Vec3,
	up: Vec3,
	reflectance: float,
	generation_comment: str,
	rng: random.Random,
	instances: bool = False,
) -> str:
	lines: List[str] = ['<?xml version="1.0" encoding="utf-8"?>', generation_comment, '<scene version="0.6.0">']

	# get the suffix of the obj filename to use as the shape type (e.g. "obj" for "quad.obj")
	type_geometry_file = Path(obj_filename).suffix.lower()[1:] # 1: to remove the leading dot

	if instances:
		group_id = f"{name_prefix}_group"
		lines.extend(
			[
				f'    <shape type="shapegroup" id="{group_id}">',
				'        <shape type="{type_geometry_file}">',
				f'            <string name="filename" value="{obj_filename}"/>',
				'            <bsdf type="diffuse">',
				f'                <rgb name="reflectance" value="{format_float(reflectance)}"/>',
				'            </bsdf>',
				'        </shape>',
				'    </shape>',
			]
		)

	for idx in range(n_objects):
		origin = sample_position(min_pos, max_pos, rng)
		direction = sample_vmf(mean_dir, kappa, rng)
		target = (
			origin[0] + direction[0],
			origin[1] + direction[1],
			origin[2] + direction[2],
		)

		if instances:
			group_id = f"{name_prefix}_group"
			lines.extend(
				[
					f'    <shape type="instance" name="{name_prefix}_{idx:05d}">',
					f'        <ref id="{group_id}"/>',
					'        <transform name="toWorld">',
					f'            <scale x="{format_float(scale[0])}" y="{format_float(scale[1])}" z="{format_float(scale[2])}"/>',
					f'            <lookAt origin="{format_vec3(origin)}" target="{format_vec3(target)}" up="{format_vec3(up)}"/>',
					'        </transform>',
					'    </shape>',
				]
			)
		else:
			lines.extend(
				[
					f'    <shape type="{type_geometry_file}" name="{name_prefix}_{idx:05d}">',
					f'        <string name="filename" value="{obj_filename}"/>',
					'        <transform name="toWorld">',
					f'            <scale x="{format_float(scale[0])}" y="{format_float(scale[1])}" z="{format_float(scale[2])}"/>',
					f'            <lookAt origin="{format_vec3(origin)}" target="{format_vec3(target)}" up="{format_vec3(up)}"/>',
					'        </transform>',
					'        <bsdf type="diffuse">',
					f'            <rgb name="reflectance" value="{format_float(reflectance)}"/>',
					'        </bsdf>',
					'    </shape>',
				]
			)

	lines.append('</scene>')
	return "\n".join(lines) + "\n"



def build_parser() -> argparse.ArgumentParser:
	parser = argparse.ArgumentParser(
		description="Generate Mitsuba XML with randomly placed/oriented obj instances."
	)
	parser.add_argument("-n", "--n-objects", type=int, required=True, help="Number of objects to instantiate.")
	parser.add_argument("-f", "--obj-filename", type=str, required=True, help="Path to the OBJ mesh.")
	parser.add_argument(
		"-d",
		"--mean-dir",
		type=float,
		nargs=3,
		metavar=("X", "Y", "Z"),
		required=True,
		help="Mean orientation direction.",
	)
	parser.add_argument(
		"-k",
		"--kappa",
		type=float,
		required=True,
		help="vMF concentration parameter (0 = uniform sphere, larger = more concentrated).",
	)
	parser.add_argument(
		"-a",
		"--min-pos",
		type=float,
		nargs=3,
		metavar=("X", "Y", "Z"),
		required=True,
		help="AABB minimum world position.",
	)
	parser.add_argument(
		"-b",
		"--max-pos",
		type=float,
		nargs=3,
		metavar=("X", "Y", "Z"),
		required=True,
		help="AABB maximum world position.",
	)
	parser.add_argument(
		"-o",
		"--output",
		type=str,
		default="-",
		help="Output XML file path. Use '-' for stdout.",
	)
	parser.add_argument(
		"-s",
		"--seed",
		type=int,
		default=None,
		help="Optional RNG seed for reproducible output.",
	)
	parser.add_argument(
		"-p",
		"--name-prefix",
		type=str,
		default="quad",
		help="Name prefix used for shape IDs.",
	)
	parser.add_argument(
		"-c",
		"--scale",
		type=float,
		nargs=3,
		metavar=("SX", "SY", "SZ"),
		default=(0.05, 0.05, 0.0005),
		help="Scale applied in the toWorld transform.",
	)
	parser.add_argument(
		"-u",
		"--up",
		type=float,
		nargs=3,
		metavar=("UX", "UY", "UZ"),
		default=(0.0, 0.0, 1.0),
		help="Up vector used in lookAt.",
	)
	parser.add_argument(
		"-r",
		"--reflectance",
		type=float,
		default=0.8,
		help="Diffuse reflectance value.",
	)
	parser.add_argument(
		"-i", 
		"--instances",
		action="store_true",
		help="Use <instance> instead of <shape> for instancing the same mesh"
	)
	return parser


def main(argv: Sequence[str] | None = None) -> int:
	parser = build_parser()
	args = parser.parse_args(argv)

	if args.n_objects < 0:
		parser.error("--n-objects must be >= 0")
	if args.kappa < 0.0:
		parser.error("--kappa must be >= 0")

	mean_dir = normalize((args.mean_dir[0], args.mean_dir[1], args.mean_dir[2]))
	min_pos = (args.min_pos[0], args.min_pos[1], args.min_pos[2])
	max_pos = (args.max_pos[0], args.max_pos[1], args.max_pos[2])
	validate_bounds(min_pos, max_pos)

	scale = (args.scale[0], args.scale[1], args.scale[2])
	up = normalize((args.up[0], args.up[1], args.up[2]))

	rng = random.Random(args.seed)
	command = get_short_invocation_command()
	generation_comment = build_generation_comment(command)

	xml = build_xml(
		n_objects=args.n_objects,
		obj_filename=args.obj_filename,
		mean_dir=mean_dir,
		kappa=args.kappa,
		min_pos=min_pos,
		max_pos=max_pos,
		name_prefix=args.name_prefix,
		scale=scale,
		up=up,
		reflectance=args.reflectance,
		generation_comment=generation_comment,
		rng=rng,
		instances=args.instances,
	)

	if args.output == "-":
		sys.stdout.write(xml)
	else:
		output_path = Path(args.output)
		output_path.parent.mkdir(parents=True, exist_ok=True)
		output_path.write_text(xml, encoding="utf-8")
		print(f"Generated geometry XML written to: {output_path}")

	return 0


if __name__ == "__main__":
	raise SystemExit(main())
